# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: altamkhan.Otterly
PackageVersion: 0.4.1
InstallerType: nullsoft
Scope: user
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ajkdrag/otterly/releases/download/v0.4.1/otterly_0.4.1_x64-setup.exe
  InstallerSha256: A96E03BD9F53299C11ED7F9CA6C772FE6DD8AA99CC75615422A8BB050225628C
ManifestType: installer
ManifestVersion: 1.12.0
